services:
  - type: web
    name: orderwhisper
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: HOST
        value: https://orderwhisper.onrender.com
      - key: SHOPIFY_APP_URL
        value: https://orderwhisper.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: orderwhisper-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: orderwhisper-redis
          type: redis
          property: connectionString
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    healthCheck:
      httpPath: /healthcheck
      period: 30
      timeout: 5
      failureThreshold: 3
      gracePeriod: 120

  - type: redis
    name: orderwhisper-redis
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

databases:
  - name: orderwhisper-db
    plan: starter
    ipAllowList: []
    postgresMajorVersion: 15 