services:
  - type: web
    name: orderwhisper
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: HOST
        value: https://orderwhisper.onrender.com
      - key: SHOPIFY_APP_URL
        value: https://orderwhisper.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: orderwhisper-db
          property: connectionString
      - key: DATABASE_SSL
        value: "true"
      - key: REDIS_URL
        fromService:
          name: orderwhisper-redis
          type: redis
          property: connectionString
      - key: REDIS_SSL
        value: "true"
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: WEBHOOK_RATE_LIMIT
        value: "50"
      - key: ENABLE_WEBHOOK_VALIDATION
        value: "true"
      - key: ENABLE_RATE_LIMITING
        value: "true"
      - key: ENABLE_MESSAGE_ENCRYPTION
        value: "true"
      - key: ENABLE_PERFORMANCE_MONITORING
        value: "true"
      - key: ENABLE_ERROR_TRACKING
        value: "true"
      - key: ENABLE_DEBUG_LOGGING
        value: "false"
      - key: ENABLE_TEST_WEBHOOKS
        value: "false"
      - key: PORT
        value: "10000"
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    healthCheck:
      httpPath: /healthcheck
      period: 30
      timeout: 5
      failureThreshold: 3
      gracePeriod: 120

  - type: redis
    name: orderwhisper-redis
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

databases:
  - name: orderwhisper-db
    plan: starter
    ipAllowList: []
    postgresMajorVersion: 15 