# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "OrderWhisper"
client_id = "10cd0ca9a3d009f3c94cedcd57d64839"
application_url = "https://merger-appointment-guest-wc.trycloudflare.com"
embedded = true
handle = "orderwhisper"
scopes = "read_orders,write_orders,read_fulfillments,write_fulfillments"
extension_directories = [ ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "orderwhisper.myshopify.com"

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"
  include_fields = [ "id", "order_number", "customer" ]

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/fulfillments/create"
  include_fields = [ "order_id", "order" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_fulfillments,write_fulfillments"

[auth]
redirect_urls = [
  "https://merger-appointment-guest-wc.trycloudflare.com/auth/callback",
  "https://merger-appointment-guest-wc.trycloudflare.com/auth/shopify/callback",
  "https://merger-appointment-guest-wc.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
