# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10cd0ca9a3d009f3c94cedcd57d64839"
extension_directories = [ ]
application_url = "https://manitoba-bahamas-qualities-sponsorship.trycloudflare.com"
embedded = true
name = "OrderWhisper"
handle = "whatsapp-notification-12"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "orderwhisper.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/fulfillments/create"
  include_fields = [ "order_id", "order" ]

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"
  include_fields = [ "id", "order_number", "customer" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://manitoba-bahamas-qualities-sponsorship.trycloudflare.com/auth/callback",
  "https://manitoba-bahamas-qualities-sponsorship.trycloudflare.com/auth/shopify/callback",
  "https://manitoba-bahamas-qualities-sponsorship.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
