# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10cd0ca9a3d009f3c94cedcd57d64839"
application_url = "https://orderwhisper.onrender.com"
embedded = true
name = "OrderWhisper"
handle = "whatsapp-notification-12"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://orderwhisper.onrender.com/api/auth",
  "https://orderwhisper.onrender.com/api/auth/callback"
]

[pos]
embedded = false
